packages:
  # AI Base 源码包
  - "AIBase_with_example/package/ai-base"
  # 业务项目 （AI Base 业务项目）
  - "frontend"
  - "backend"
  # AI Base demo 项目
  - "AIBase_with_example"
overrides:
  "@types/react": "^19.2.17"
  "@types/react-dom": "^19.2.3"