-- 增量：对齐 create/update_entity 字段 schema（enumCode）与枚举修复指引
-- 用法：psql -f scripts/migrate-bizdata-enum-field-schema.sql

UPDATE aibase.tools SET
    description = '创建 ER/JSON 实体；status/state/*_type 须先 create_enum，字段 type=adb-enum + enumCode',
    parameters_schema = '{"type":"object","properties":{"code":{"type":"string"},"label":{"type":"string"},"entityKind":{"type":"string","enum":["er_table","json_schema"]},"tableName":{"type":"string"},"fields":{"type":"array","description":"字段列表；status/state/*_type 等须 type=adb-enum 并指定 enumCode（先 bizdata_create_enum）","items":{"type":"object","properties":{"fieldKey":{"type":"string"},"name":{"type":"string","description":"同 fieldKey"},"label":{"type":"string"},"type":{"type":"string","description":"varchar/int/uuid/decimal 等；有限取值须用 adb-enum（配合 enumCode）"},"enumCode":{"type":"string","description":"枚举 code（如 production:WorkOrderStatus）；type=adb-enum 时必填"},"extendType":{"type":"string","description":"扩展类型；枚举可写 adb-enum（与 type=adb-enum 等价）"},"enumConfig":{"type":"object","properties":{"enumCode":{"type":"string"},"isMultiple":{"type":"boolean"}}},"length":{"type":"integer"},"nullable":{"type":"boolean"},"unique":{"type":"boolean"},"primary":{"type":"boolean"},"columnInfo":{"type":"object"},"typeormConfig":{"type":"object"}}}},"indexes":{"type":"array","items":{"type":"object"}},"relations":{"type":"array","items":{"type":"object"}}},"required":["code","label"]}'::jsonb,
    review_markdown = E'## bizdata_create_entity\n\ncode 格式 `Scope1[:Scope2...]:EntityName`。**仅用于 code 不存在的新实体**；若已存在请用 `bizdata_rename_entity_code`。推荐同时传 fields、indexes、relations；分步则须 upsert_entity_indexes 与 add_relation。**禁止** delete + create 改 Scope。\n\n### 枚举字段（status/state/*_type 等）\n**禁止**用 varchar。流程：\n1. `bizdata_list_enums`\n2. 无则 `bizdata_create_enum`（code + values）\n3. 字段**同时**传 `type` 与 `enumCode`：\n```json\n{ "fieldKey": "station_type", "type": "adb-enum", "enumCode": "fmms:StationType", "label": "站点类型" }\n```\n禁止只改 `typeormConfig.type`，或只传 `type=adb-enum` 不传 `enumCode`。',
    updated_at = CURRENT_TIMESTAMP
WHERE function_name = 'bizdata_create_entity';

UPDATE aibase.tools SET
    description = '更新实体信息与字段；有限取值字段须 type=adb-enum + enumCode（先 create_enum）',
    parameters_schema = '{"type":"object","properties":{"entityId":{"type":"string"},"entityCode":{"type":"string","description":"定位用：当前/旧 code"},"code":{"type":"string","description":"新 code，如 fmms:production:WorkCard"},"label":{"type":"string"},"tableName":{"type":"string","description":"ER 物理表名；默认推导时随 code 变"},"status":{"type":"string","enum":["enabled","disabled","archived"]},"replaceFields":{"type":"boolean"},"layout":{"type":"object","description":"实体 layout，含 indexes 等"},"jsonSchema":{"type":"object","description":"JSON Schema 结构"},"fields":{"type":"array","description":"字段列表；status/state/*_type 等须 type=adb-enum 并指定 enumCode（先 bizdata_create_enum）","items":{"type":"object","properties":{"fieldKey":{"type":"string"},"name":{"type":"string","description":"同 fieldKey"},"label":{"type":"string"},"type":{"type":"string","description":"varchar/int/uuid/decimal 等；有限取值须用 adb-enum（配合 enumCode）"},"enumCode":{"type":"string","description":"枚举 code（如 production:WorkOrderStatus）；type=adb-enum 时必填"},"extendType":{"type":"string","description":"扩展类型；枚举可写 adb-enum（与 type=adb-enum 等价）"},"enumConfig":{"type":"object","properties":{"enumCode":{"type":"string"},"isMultiple":{"type":"boolean"}}},"length":{"type":"integer"},"nullable":{"type":"boolean"},"unique":{"type":"boolean"},"primary":{"type":"boolean"},"columnInfo":{"type":"object"},"typeormConfig":{"type":"object"}}}}}}'::jsonb,
    review_markdown = E'## bizdata_update_entity\n\n保存后 version 自增，**页面 UI 会自动同步**，无需用户手动刷新。\n\n### 定位实体\n- entityId 或 **entityCode**（当前/旧 code，如 `fmms:WorkCard`）二选一\n\n### 修改 Code（重要）\n- 传 `code` 为新 code，格式 `Scope1[:Scope2...]:EntityName`（如 `fmms:production:WorkCard`）\n- 可选 `tableName`（ER）；不填且原表名为默认推导值时随 code 同步\n- 后端**同一事务**级联更新：元数据、绑定 API 服务、采集管道、物化记录、关系 config、字段/脚本引用\n- **任一步失败则全部回滚**；须向用户展示 Tool 错误原文，禁止声称成功\n- 成功后用**新 code** 调 `bizdata_get_entity` / `bizdata_list_entity_summaries` 验证，并重跑 `bizdata_validate_model`\n- **禁止**为改 Scope 而 delete + create\n\n### 字段格式\n普通字段：\n```json\n{ "fieldKey": "company_name", "label": "公司名称", "type": "varchar", "length": 255, "nullable": false }\n```\n\n### 枚举字段（status/state/*_type 等，必遵）\n**禁止**用 varchar。修复/新增流程：\n1. `bizdata_list_enums` → 无则 `bizdata_create_enum`（code + values）\n2. `bizdata_update_entity` **同时**传 `type` 与 `enumCode`：\n```json\n{ "fieldKey": "station_type", "type": "adb-enum", "enumCode": "fmms:StationType", "label": "站点类型" }\n```\n3. 再 `bizdata_validate_model`\n\n**禁止**：只改 `typeormConfig.type`；只传 `type=adb-enum` 不传 `enumCode`；用 varchar 建 status/*_type。\n\n### 索引与关系\n- 索引请用 **bizdata_upsert_entity_indexes**\n- 关系请用 **bizdata_add_relation** + **bizdata_list_relations**\n\n### 合并策略\n- 默认 merge：只传新增/修改字段，保留已有字段\n- replaceFields=true：全量替换\n\n### 页面上下文\n- 可用 `aibase_read_surfaces` 读取当前选中实体等页面状态',
    updated_at = CURRENT_TIMESTAMP
WHERE function_name = 'bizdata_update_entity';

UPDATE aibase.tools SET
    description = '创建 ADB 枚举；有限取值字段须先建枚举，再在实体字段用 type=adb-enum + enumCode 引用',
    review_markdown = E'## bizdata_create_enum\n\ncode 如 `production:WorkOrderStatus` / `fmms:StationType`。推荐同时传 values + items；仅 values 时服务端补 items。\n\n### 引用到实体字段（create/update_entity 时必传 enumCode）\n```json\n{ "fieldKey": "station_type", "type": "adb-enum", "enumCode": "fmms:StationType", "label": "站点类型" }\n```\n禁止只传 `type=adb-enum` 而不传 `enumCode`。',
    updated_at = CURRENT_TIMESTAMP
WHERE function_name = 'bizdata_create_enum';

UPDATE aibase.tools SET
    description = '校验实体模型完整性；status/*_type 须为 adb-enum+enumCode；失败时按 errors 先 create_enum 再 update',
    review_markdown = E'## bizdata_validate_model\n\n**每个实体创建/修改后必须调用**（传 entityCode）。\n\n- 默认 markValidated=true：isValid 为 true 时自动标记「验证通过」\n- 若报「疑似状态/类型字段」或「缺少 enumCode」：先 `bizdata_list_enums` / `bizdata_create_enum`，再 `bizdata_update_entity` **同时**传 `type=adb-enum` + `enumCode`，然后重跑本 Tool\n- 批量创建后须对每个实体各调用一次',
    updated_at = CURRENT_TIMESTAMP
WHERE function_name = 'bizdata_validate_model';

UPDATE aibase.skills SET
    content_markdown = E'# 业务数据模型设计助手\n\n你是 EADAF 业务数据建模助手。**禁止**只建空实体或只写字段就结束。\n\n## 编码规范\n- Entity code：`Scope1[:Scope2...]:EntityName`（如 `fmms:production:WorkCard`、`sales:order:Order`）\n- Enum code：同 Scope 层级 + 枚举名（如 `fmms:production:WorkCardStatus`）\n- Scope 树由实体 code 冒号路径推导，**无独立 create_scope Tool**\n\n## Scope 调整 / 修改实体 Code（必遵）\n- **唯一推荐**：**`bizdata_rename_entity_code`**，仅传 `entityCode`（旧）+ `code`（新）\n- 备选：`bizdata_update_entity` 同样仅传 entityCode + code\n- **禁止** `bizdata_delete_entity` + `bizdata_create_entity`（丢失物化/MOCK/关系，且常虚假成功）\n- 批量改 Scope：list_entity_summaries → 逐个 rename_entity_code → 再 list_entity_summaries 验证 → validate_model\n- 必须以 Tool 返回的 `_verification.verified=true` 为准汇报成功\n\n## 修改实体 Code（级联）\n- 后端同一事务级联更新元数据、API 服务、采集管道、物化记录、关系 config、字段/脚本引用；失败则全部回滚\n- 若表名随 code 变更，已物化连接上的物理表/集合会自动重命名（无需重新物化 DDL）\n\n## 完整建模（必遵）\n1. **枚举**：status/state/*_type 等 → `bizdata_list_enums` / `bizdata_create_enum`，字段用 `type: adb-enum` + `enumCode`（禁止 varchar）\n2. **字段**：`bizdata_create_entity` / `bizdata_update_entity` 传 fields（枚举字段必须同时带 enumCode）\n3. **索引（必做）**：`bizdata_upsert_entity_indexes` 或 create 时传 indexes\n4. **关系（必做）**：`bizdata_add_relation` 或 create 时传 relations，再 `bizdata_list_relations` 验证\n5. **校验**：`bizdata_validate_model` 每个实体必调（entityCode，markValidated 默认 true）\n\n## 枚举字段修复（校验失败时必遵）\n若 `bizdata_validate_model` 报「疑似状态/类型字段」或 `bizdata_update_entity` 报「缺少 enumCode」：\n1. `bizdata_list_enums`\n2. 无则 `bizdata_create_enum`（code + values）\n3. `bizdata_update_entity` **同时**传：`{ "fieldKey": "station_type", "type": "adb-enum", "enumCode": "fmms:StationType", "label": "站点类型" }`\n4. 再 `bizdata_validate_model`\n\n**禁止**：只改 `typeormConfig.type`；只传 `type=adb-enum` 不传 `enumCode`；用 varchar 建 status/*_type。\n\n## 实体列表 Tool 选用\n- **浏览 / 批量 / Scope 调整**：优先 **`bizdata_list_entity_summaries`**（不含 fields，含 fieldCount）\n- **单实体字段详情**：`bizdata_get_entity`（传 entityCode）\n- **`bizdata_list_entities`**：已对 AI 停用；需要字段请 `bizdata_get_entity`\n\n## 验证通过标记\n- 新建实体默认未验证通过\n- 批量创建后须对每个实体调用 `bizdata_validate_model`，isValid 为 true 时自动标记验证通过\n- 校验失败则按「枚举字段修复」步骤修复后重新校验\n\n## 连续执行（重要）\n用户确认「开始」「继续」「完善」后，须**连续调用 Tool** 完成枚举→字段→索引→关系→**校验**，**禁止**做完一步只输出「第N步」叙述就停。\n- 写了「第五步：模型校验」必须立刻对每个实体调用 `bizdata_validate_model`（entityCode）。\n\n## ID 规则\n- 禁止编造 entityId；用 entityCode 或 list 返回的 UUID\n\n## UI 同步\n- 写操作成功后前端会自动刷新，不要提示用户手动刷新\n\n## 阶段边界（必遵）\n- **默认任务范围**：仅**逻辑模型**（枚举 → 字段 → 索引 → 关系 → `bizdata_validate_model` 校验）\n- 全部目标实体的 `bizdata_validate_model` 均 isValid=true 后，**本阶段结束**，停止 Tool 调用\n- **禁止**在本阶段调用：物化、MOCK 数据、API 服务、指标、采集管道\n- 仅当用户**明确**要求「一并物化 / 创建 API / 创建指标 / 全套服务」时，才在总结中说明需切换对应页面\n\n## 阶段完成后的下一步（A2UI）\n全部实体校验通过后，按 **aibase-chat-framework** 约定，在回复末尾输出 `a2ui-commands` 块（见全局 Framework Skill），建议 materialize / create_api / create_metrics / refine_model 等 3～5 条。',
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'bizdata-model-design';
