/**
 * EADAF 业务 Tool 语义化展示名（注入 @eadaf/ai-base，不写进内核包）。
 */
export const EADAF_TOOL_DISPLAY_NAMES: Record<string, string> = {
  bizdata_list_entities: '列出实体(全量字段,已停用)',
  bizdata_list_entity_summaries: '列出实体摘要',
  bizdata_entity: '业务实体（读）',
  bizdata_get_entity: '获取实体详情',
  bizdata_exists_entity: '判断实体是否存在',
  bizdata_exists_enum: '判断枚举是否存在',
  bizdata_exists_scope: '判断 Scope 是否存在',
  bizdata_create_entity: '创建实体',
  bizdata_update_entity: '更新实体',
  bizdata_rename_entity_code: '重命名实体 Code',
  bizdata_delete_entity: '删除实体',
  bizdata_create_enum: '创建枚举',
  bizdata_update_enum: '更新枚举',
  bizdata_list_enums: '列出枚举',
  bizdata_list_relations: '列出实体关系',
  bizdata_query_relation_graph: '查询关系图谱',
  bizdata_add_relation: '添加实体关系',
  bizdata_delete_relation: '删除实体关系',
  bizdata_upsert_entity_indexes: '更新实体索引',
  bizdata_validate_model: '校验模型',
  bizdata_get_scope_description: '读取 Scope 业务说明',
  bizdata_upsert_scope_description: '写入 Scope 业务说明',
  bizdata_preview_materialization: '物化预览',
  bizdata_execute_materialization: '执行物化',
  bizdata_list_materialization_runs: '物化历史',
  bizdata_get_materialization_status: '物化状态',
  bizdata_browse_materialized_schema: '浏览物化表结构',
  bizdata_browse_materialized_rows: '浏览物化表数据',
  bizdata_insert_mock_data: '插入MOCK数据',
  bizdata_list_data_standards: '列出数据标准',
  bizdata_create_data_standard: '创建数据标准',
  bizdata_update_data_standard: '更新数据标准',
  bizdata_delete_data_standard: '删除数据标准',
  bizdata_list_metadata_tables: '列出元数据表',
  bizdata_get_metadata_table: '获取元数据表',
  bizdata_get_metadata_by_target: '按 target 获取元数据',
  bizdata_upsert_metadata_table: '保存元数据表',
  bizdata_update_metadata_table: '更新元数据表',
  bizdata_upsert_metadata_field: '保存元数据字段',
  bizdata_update_metadata_fields: '批量更新元数据字段',
  bizdata_sync_metadata_from_schema: '同步元数据骨架',
  apiservice_create_service: '创建 API 服务',
  apiservice_create_services_batch: '批量创建 API 服务',
  apiservice_list_services: '列出 API 服务',
  apiservice_list_draft_services: '列出未发布 API',
  apiservice_filter_services: '过滤 API 服务',
  apiservice_get_service: '获取 API 服务',
  apiservice_resolve_connection: '解析 API 连接',
  apiservice_check_handler: '检查 Handler',
  apiservice_publish_service: '发布 API 服务',
  apiservice_run_test: '测试 API 服务',
  apiservice_update_service: '更新 API 服务',
  apiservice_delete_service: '删除 API 服务',
  apiservice_list_operations: '列出 API 操作',
  apiservice_get_tree: '获取 API 树',
  apiservice_get_test_profile: '获取测试配置',
  apiservice_suggest_test_params: '建议测试参数',
  apiservice_set_test_params: '设置测试参数',
  apiservice_navigate: '跳转 API 页',
  apiservice_list_exception_responses: '列出异常响应',
  apiservice_create_exception_response: '创建异常响应',
  apiservice_update_exception_response: '更新异常响应',
  apiservice_delete_exception_response: '删除异常响应',
  bizdata_metric_list: '列出指标',
  bizdata_metric_filter: '过滤指标',
  bizdata_metric_get: '获取指标',
  bizdata_metric_upsert: '保存指标',
  bizdata_metric_delete: '删除指标',
  bizdata_metric_execute: '执行指标',
  bizdata_metric_execute_batch: '批量执行指标',
  bizdata_metric_list_runs: '指标执行历史',
  bizdata_metric_list_values: '列出指标值',
  bizdata_metric_get_value: '获取指标值',
  bizdata_metric_get_dashboard: '获取指标看板',
  bizdata_metric_card_list: '列出指标卡片',
  bizdata_metric_card_get: '获取指标卡片',
  bizdata_metric_card_upsert: '保存指标卡片',
  bizdata_metric_card_delete: '删除指标卡片',
  bizdata_metric_card_suggest: '建议指标卡片',
  bizdata_metric_suggest_definition: '建议指标定义',
  bizdata_metric_navigate: '跳转指标页',
};
