/**
 * 内置 API 清单（固定、只读、由开发者随后端路由同步维护）
 *
 * - 清单是内置 API 的单一事实源（Single Source of Truth）：随对应路由的开发同步增改。
 * - code 采用「业务域:资源[:动作]」分层（用 `:` 分隔，前端据此自动建树），不再使用 `api:` 前缀。
 * - routePath 存储完整路径（含 /api/v1 前缀），供运行时路由匹配直接使用 ctx.path。
 * - httpMethods 大写。
 *
 * 域划分（与导航菜单对应）：
 *   user              用户（账户）相关
 *   organization      组织（部门）相关
 *   authorization     角色与权限相关
 *   storage           文件存储（Bucket / 文件）
 *   bizdata           业务数据（实体 / 物化 / 数据库连接 / 数据标准 / 元数据）
 *   bizdata:metrics   业务数据 - 指标
 *   bizdata:collection 业务数据 - 采集管道
 *   ai                AI 能力（服务商 / 模型 / Scope / Tool / Skill / 请求日志 / 运行时）
 *   system            系统设置（功能开关 / 备份）
 *
 * 【不纳入清单的端点】
 *   - Auth 认证（/api/v1/auth/*）：外部应用通过应用令牌（app_secret → JWT）访问，不应使用登录认证。
 *   - 应用管理（/api/v1/applications/*）：避免外部应用管理其他应用（含安全隐患）。
 *   - 修改个人资料（users/:user_id 的 update / avatar / change-password，及 auth/check 获取当前用户信息）：
 *     属于登录用户的个人操作，不应对外开放。
 */
const BUILTIN_API_CATALOG = [
  // ===== user 域：账户（管理员视角的用户管理，不含个人资料修改） =====
  {
    code: 'user:account:list',
    domain: 'user',
    label: '用户列表',
    routePath: '/api/v1/users',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取用户列表',
  },
  {
    code: 'user:account:create',
    domain: 'user',
    label: '创建用户',
    routePath: '/api/v1/users',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建用户',
  },
  {
    code: 'user:account:get',
    domain: 'user',
    label: '用户详情',
    routePath: '/api/v1/users/:user_id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取用户详情',
  },
  {
    code: 'user:account:delete',
    domain: 'user',
    label: '删除用户',
    routePath: '/api/v1/users/:user_id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除用户',
  },
  {
    code: 'user:account:assign_roles',
    domain: 'user',
    label: '分配用户角色',
    routePath: '/api/v1/users/:user_id/roles',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '为用户分配角色',
  },
  {
    code: 'user:account:update_status',
    domain: 'user',
    label: '更新用户状态',
    routePath: '/api/v1/users/:user_id/status',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '更新用户启用/禁用状态',
  },
  {
    code: 'user:account:restore',
    domain: 'user',
    label: '恢复用户',
    routePath: '/api/v1/users/:user_id/restore',
    httpMethods: ['POST'],
    actions: ['update'],
    description: '恢复已删除用户',
  },

  // ===== organization 域：部门 =====
  {
    code: 'organization:department:list',
    domain: 'organization',
    label: '部门列表',
    routePath: '/api/v1/departments',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取部门列表',
  },
  {
    code: 'organization:department:create',
    domain: 'organization',
    label: '创建部门',
    routePath: '/api/v1/departments',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建部门',
  },
  {
    code: 'organization:department:get',
    domain: 'organization',
    label: '部门详情',
    routePath: '/api/v1/departments/:department_id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取部门详情',
  },
  {
    code: 'organization:department:update',
    domain: 'organization',
    label: '更新部门',
    routePath: '/api/v1/departments/:department_id',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '更新部门信息',
  },
  {
    code: 'organization:department:delete',
    domain: 'organization',
    label: '删除部门',
    routePath: '/api/v1/departments/:department_id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除部门',
  },
  {
    code: 'organization:department:tree',
    domain: 'organization',
    label: '部门树',
    routePath: '/api/v1/departments/tree',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取部门树形结构',
  },
  {
    code: 'organization:department:members',
    domain: 'organization',
    label: '部门成员',
    routePath: '/api/v1/departments/:department_id/users',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取部门下的成员列表',
  },
  {
    code: 'organization:department:assign_roles',
    domain: 'organization',
    label: '分配部门角色',
    routePath: '/api/v1/departments/:department_id/roles',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '为部门分配角色',
  },

  // ===== authorization 域：角色 =====
  {
    code: 'authorization:role:list',
    domain: 'authorization',
    label: '角色列表',
    routePath: '/api/v1/roles',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取角色列表',
  },
  {
    code: 'authorization:role:create',
    domain: 'authorization',
    label: '创建角色',
    routePath: '/api/v1/roles',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建角色',
  },
  {
    code: 'authorization:role:get',
    domain: 'authorization',
    label: '角色详情',
    routePath: '/api/v1/roles/:role_id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取角色详情',
  },
  {
    code: 'authorization:role:update',
    domain: 'authorization',
    label: '更新角色',
    routePath: '/api/v1/roles/:role_id',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '更新角色信息',
  },
  {
    code: 'authorization:role:delete',
    domain: 'authorization',
    label: '删除角色',
    routePath: '/api/v1/roles/:role_id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除角色',
  },
  {
    code: 'authorization:role:assign_permissions',
    domain: 'authorization',
    label: '分配角色权限',
    routePath: '/api/v1/roles/:role_id/permissions',
    httpMethods: ['POST'],
    actions: ['update'],
    description: '为角色分配权限',
  },
  {
    code: 'authorization:role:update_permissions',
    domain: 'authorization',
    label: '更新角色权限',
    routePath: '/api/v1/roles/:role_id/permissions',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '更新角色权限',
  },
  {
    code: 'authorization:role:check_permission',
    domain: 'authorization',
    label: '校验权限',
    routePath: '/api/v1/roles/check-permission',
    httpMethods: ['POST'],
    actions: ['read'],
    description: '校验用户是否具备指定权限',
  },

  // ===== authorization 域：权限 =====
  {
    code: 'authorization:permission:list',
    domain: 'authorization',
    label: '权限列表',
    routePath: '/api/v1/permissions',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取权限列表',
  },
  {
    code: 'authorization:permission:create',
    domain: 'authorization',
    label: '创建权限',
    routePath: '/api/v1/permissions',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建权限',
  },
  {
    code: 'authorization:permission:get',
    domain: 'authorization',
    label: '权限详情',
    routePath: '/api/v1/permissions/:permission_id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取权限详情',
  },
  {
    code: 'authorization:permission:update',
    domain: 'authorization',
    label: '更新权限',
    routePath: '/api/v1/permissions/:permission_id',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '更新权限信息',
  },
  {
    code: 'authorization:permission:delete',
    domain: 'authorization',
    label: '删除权限',
    routePath: '/api/v1/permissions/:permission_id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除权限',
  },

  // ===== storage 域：文件存储 - Bucket =====
  {
    code: 'storage:bucket:list',
    domain: 'storage',
    label: 'Bucket 列表',
    routePath: '/api/v1/storage/buckets',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 Bucket 列表',
  },
  {
    code: 'storage:bucket:create',
    domain: 'storage',
    label: '创建 Bucket',
    routePath: '/api/v1/storage/buckets',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建 Bucket',
  },
  {
    code: 'storage:bucket:get',
    domain: 'storage',
    label: 'Bucket 详情',
    routePath: '/api/v1/storage/buckets/:id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 Bucket 详情',
  },
  {
    code: 'storage:bucket:update',
    domain: 'storage',
    label: '更新 Bucket',
    routePath: '/api/v1/storage/buckets/:id',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '更新 Bucket',
  },
  {
    code: 'storage:bucket:delete',
    domain: 'storage',
    label: '删除 Bucket',
    routePath: '/api/v1/storage/buckets/:id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除 Bucket',
  },

  // ===== storage 域：文件存储 - 文件 =====
  {
    code: 'storage:object:list',
    domain: 'storage',
    label: '文件列表',
    routePath: '/api/v1/storage/objects',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取文件列表（文件浏览器）',
  },
  {
    code: 'storage:object:upload',
    domain: 'storage',
    label: '上传文件',
    routePath: '/api/v1/storage/objects/upload',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '上传文件到 Bucket',
  },
  {
    code: 'storage:object:download',
    domain: 'storage',
    label: '下载文件',
    routePath: '/api/v1/storage/objects/:id/download',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '下载文件',
  },
  {
    code: 'storage:object:preview',
    domain: 'storage',
    label: '预览文件',
    routePath: '/api/v1/storage/objects/:id/preview',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '预览文件（图片 inline）',
  },

  // ===== bizdata 域：业务数据 - 实体 =====
  {
    code: 'bizdata:entity:schema',
    domain: 'bizdata',
    label: '数据模型快照',
    routePath: '/api/v1/business-data/schema',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取业务数据模型全量快照',
  },
  {
    code: 'bizdata:scope:list',
    domain: 'bizdata',
    label: '业务 Scope 列表',
    routePath: '/api/v1/business-data/scopes',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取业务数据 Scope 树',
  },
  {
    code: 'bizdata:entity:list',
    domain: 'bizdata',
    label: '实体列表',
    routePath: '/api/v1/business-data/entities',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取实体列表',
  },
  {
    code: 'bizdata:entity:create',
    domain: 'bizdata',
    label: '创建实体',
    routePath: '/api/v1/business-data/entities',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建实体',
  },
  {
    code: 'bizdata:entity:get',
    domain: 'bizdata',
    label: '实体详情',
    routePath: '/api/v1/business-data/entities/:id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取实体详情',
  },
  {
    code: 'bizdata:entity:update',
    domain: 'bizdata',
    label: '更新实体',
    routePath: '/api/v1/business-data/entities/:id',
    httpMethods: ['PATCH'],
    actions: ['update'],
    description: '更新实体',
  },
  {
    code: 'bizdata:entity:delete',
    domain: 'bizdata',
    label: '删除实体',
    routePath: '/api/v1/business-data/entities/:id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除实体',
  },
  {
    code: 'bizdata:entity:save_fields',
    domain: 'bizdata',
    label: '保存实体字段',
    routePath: '/api/v1/business-data/entities/:id/fields',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '批量保存实体字段',
  },

  // ===== bizdata 域：业务数据 - 枚举 / 关系 =====
  {
    code: 'bizdata:enum:list',
    domain: 'bizdata',
    label: '枚举列表',
    routePath: '/api/v1/business-data/enums',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取枚举列表',
  },
  {
    code: 'bizdata:enum:create',
    domain: 'bizdata',
    label: '创建枚举',
    routePath: '/api/v1/business-data/enums',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建枚举',
  },
  {
    code: 'bizdata:relation:list',
    domain: 'bizdata',
    label: '关系列表',
    routePath: '/api/v1/business-data/relations',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取实体关系列表',
  },
  {
    code: 'bizdata:relation:create',
    domain: 'bizdata',
    label: '创建关系',
    routePath: '/api/v1/business-data/relations',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建实体关系',
  },

  // ===== bizdata 域：业务数据 - 物化 =====
  {
    code: 'bizdata:materialization:preview',
    domain: 'bizdata',
    label: '物化预览',
    routePath: '/api/v1/business-data/materialization/preview',
    httpMethods: ['POST'],
    actions: ['read'],
    description: '物化预览（SQL + TS 代码）',
  },
  {
    code: 'bizdata:materialization:execute',
    domain: 'bizdata',
    label: '执行物化',
    routePath: '/api/v1/business-data/materialization/execute',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '执行物化',
  },
  {
    code: 'bizdata:materialization:status',
    domain: 'bizdata',
    label: '物化状态',
    routePath: '/api/v1/business-data/materialization/status',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '各实体物化版本与 stale 状态',
  },
  {
    code: 'bizdata:materialization:runs',
    domain: 'bizdata',
    label: '物化历史',
    routePath: '/api/v1/business-data/materialization/runs',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '物化历史列表',
  },
  {
    code: 'bizdata:materialization:table_schema',
    domain: 'bizdata',
    label: '物化表结构',
    routePath: '/api/v1/business-data/materialization/tables/:entityId/schema',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '浏览物化物理表结构',
  },
  {
    code: 'bizdata:materialization:table_rows',
    domain: 'bizdata',
    label: '物化表数据',
    routePath: '/api/v1/business-data/materialization/tables/:entityId/rows',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '分页浏览物化物理表数据',
  },

  // ===== bizdata 域：业务数据 - 数据库连接 =====
  {
    code: 'bizdata:connection:list',
    domain: 'bizdata',
    label: '数据库连接列表',
    routePath: '/api/v1/business-data/database-connections',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取数据库连接列表',
  },
  {
    code: 'bizdata:connection:create',
    domain: 'bizdata',
    label: '创建数据库连接',
    routePath: '/api/v1/business-data/database-connections',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建数据库连接',
  },
  {
    code: 'bizdata:connection:test',
    domain: 'bizdata',
    label: '测试数据库连接',
    routePath: '/api/v1/business-data/database-connections/:id/test',
    httpMethods: ['POST'],
    actions: ['read'],
    description: '测试数据库连接',
  },

  // ===== bizdata 域：业务数据 - 数据标准 / 元数据 =====
  {
    code: 'bizdata:data_standard:list',
    domain: 'bizdata',
    label: '数据标准列表',
    routePath: '/api/v1/business-data/data-standards',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取数据标准列表',
  },
  {
    code: 'bizdata:data_standard:create',
    domain: 'bizdata',
    label: '创建数据标准',
    routePath: '/api/v1/business-data/data-standards',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建数据标准',
  },
  {
    code: 'bizdata:metadata:tables',
    domain: 'bizdata',
    label: '元数据表列表',
    routePath: '/api/v1/business-data/metadata/tables',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取元数据逻辑表列表',
  },
  {
    code: 'bizdata:metadata:upsert_table',
    domain: 'bizdata',
    label: '保存元数据表',
    routePath: '/api/v1/business-data/metadata/tables',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建或按 target 保存元数据表',
  },

  // ===== bizdata:metrics 域：业务数据 - 指标 =====
  {
    code: 'bizdata:metrics:dashboard',
    domain: 'bizdata:metrics',
    label: '指标看板',
    routePath: '/api/v1/business-data/metrics/dashboard',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '指标看板聚合',
  },
  {
    code: 'bizdata:metrics:list',
    domain: 'bizdata:metrics',
    label: '指标列表',
    routePath: '/api/v1/business-data/metrics',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取指标列表',
  },
  {
    code: 'bizdata:metrics:create',
    domain: 'bizdata:metrics',
    label: '创建指标',
    routePath: '/api/v1/business-data/metrics',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建指标',
  },
  {
    code: 'bizdata:metrics:get',
    domain: 'bizdata:metrics',
    label: '指标详情',
    routePath: '/api/v1/business-data/metrics/:id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取指标详情',
  },
  {
    code: 'bizdata:metrics:update',
    domain: 'bizdata:metrics',
    label: '更新指标',
    routePath: '/api/v1/business-data/metrics/:id',
    httpMethods: ['PATCH'],
    actions: ['update'],
    description: '更新指标',
  },
  {
    code: 'bizdata:metrics:delete',
    domain: 'bizdata:metrics',
    label: '删除指标',
    routePath: '/api/v1/business-data/metrics/:id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除指标',
  },
  {
    code: 'bizdata:metrics:execute',
    domain: 'bizdata:metrics',
    label: '执行指标',
    routePath: '/api/v1/business-data/metrics/:id/execute',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '手动执行指标',
  },
  {
    code: 'bizdata:metrics:value',
    domain: 'bizdata:metrics',
    label: '指标最新值',
    routePath: '/api/v1/business-data/metrics/:id/value',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取指标最新值',
  },

  // ===== bizdata:collection 域：业务数据 - 采集管道 =====
  {
    code: 'bizdata:collection:list',
    domain: 'bizdata:collection',
    label: '采集管道列表',
    routePath: '/api/v1/business-data/collection-pipelines',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取采集管道列表',
  },
  {
    code: 'bizdata:collection:create',
    domain: 'bizdata:collection',
    label: '创建采集管道',
    routePath: '/api/v1/business-data/collection-pipelines',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建采集管道',
  },
  {
    code: 'bizdata:collection:get',
    domain: 'bizdata:collection',
    label: '采集管道详情',
    routePath: '/api/v1/business-data/collection-pipelines/:id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取采集管道详情',
  },
  {
    code: 'bizdata:collection:update',
    domain: 'bizdata:collection',
    label: '更新采集管道',
    routePath: '/api/v1/business-data/collection-pipelines/:id',
    httpMethods: ['PATCH'],
    actions: ['update'],
    description: '更新采集管道',
  },
  {
    code: 'bizdata:collection:delete',
    domain: 'bizdata:collection',
    label: '删除采集管道',
    routePath: '/api/v1/business-data/collection-pipelines/:id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除采集管道',
  },
  {
    code: 'bizdata:collection:publish',
    domain: 'bizdata:collection',
    label: '发布采集管道',
    routePath: '/api/v1/business-data/collection-pipelines/:id/publish',
    httpMethods: ['POST'],
    actions: ['update'],
    description: '发布采集管道',
  },

  // ===== ai 域：AI 服务商 / 模型 =====
  {
    code: 'ai:provider:list',
    domain: 'ai',
    label: 'AI 服务商列表',
    routePath: '/api/v1/admin/providers',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AI 服务商列表',
  },
  {
    code: 'ai:provider:create',
    domain: 'ai',
    label: '创建 AI 服务商',
    routePath: '/api/v1/admin/providers',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建 AI 服务商',
  },
  {
    code: 'ai:provider:get',
    domain: 'ai',
    label: 'AI 服务商详情',
    routePath: '/api/v1/admin/providers/:id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AI 服务商详情',
  },
  {
    code: 'ai:provider:update',
    domain: 'ai',
    label: '更新 AI 服务商',
    routePath: '/api/v1/admin/providers/:id',
    httpMethods: ['PATCH'],
    actions: ['update'],
    description: '更新 AI 服务商',
  },
  {
    code: 'ai:provider:delete',
    domain: 'ai',
    label: '删除 AI 服务商',
    routePath: '/api/v1/admin/providers/:id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除 AI 服务商',
  },
  {
    code: 'ai:model:list',
    domain: 'ai',
    label: 'AI 模型列表',
    routePath: '/api/v1/admin/models',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AI 模型列表',
  },
  {
    code: 'ai:model:create',
    domain: 'ai',
    label: '创建 AI 模型',
    routePath: '/api/v1/admin/models',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建 AI 模型',
  },
  {
    code: 'ai:model:get',
    domain: 'ai',
    label: 'AI 模型详情',
    routePath: '/api/v1/admin/models/:id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AI 模型详情',
  },
  {
    code: 'ai:model:update',
    domain: 'ai',
    label: '更新 AI 模型',
    routePath: '/api/v1/admin/models/:id',
    httpMethods: ['PATCH'],
    actions: ['update'],
    description: '更新 AI 模型',
  },
  {
    code: 'ai:model:delete',
    domain: 'ai',
    label: '删除 AI 模型',
    routePath: '/api/v1/admin/models/:id',
    httpMethods: ['DELETE'],
    actions: ['delete'],
    description: '删除 AI 模型',
  },

  // ===== ai 域：AI Scope / Tool / Skill / 请求日志 =====
  {
    code: 'ai:scope:list',
    domain: 'ai',
    label: 'AI Scope 列表',
    routePath: '/api/v1/admin/scopes',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AI Scope 列表',
  },
  {
    code: 'ai:scope:create',
    domain: 'ai',
    label: '创建 AI Scope',
    routePath: '/api/v1/admin/scopes',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建 AI Scope',
  },
  {
    code: 'ai:tool:list',
    domain: 'ai',
    label: 'AI Tool 列表',
    routePath: '/api/v1/admin/tools',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AI Tool 列表',
  },
  {
    code: 'ai:tool:create',
    domain: 'ai',
    label: '创建 AI Tool',
    routePath: '/api/v1/admin/tools',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建 AI Tool',
  },
  {
    code: 'ai:tool:invoke',
    domain: 'ai',
    label: '执行 AI Tool',
    routePath: '/api/v1/ai/tools/invoke',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '执行 Server Tool（functionName + arguments）',
  },
  {
    code: 'ai:skill:list',
    domain: 'ai',
    label: 'AI Skill 列表',
    routePath: '/api/v1/admin/skills',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AI Skill 列表',
  },
  {
    code: 'ai:skill:create',
    domain: 'ai',
    label: '创建 AI Skill',
    routePath: '/api/v1/admin/skills',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '创建 AI Skill',
  },
  {
    code: 'ai:request_log:list',
    domain: 'ai',
    label: 'AI 请求日志列表',
    routePath: '/api/v1/admin/ai-request-logs',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AI 请求日志列表',
  },
  {
    code: 'ai:request_log:get',
    domain: 'ai',
    label: 'AI 请求日志详情',
    routePath: '/api/v1/admin/ai-request-logs/:id',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AI 请求日志详情',
  },

  // ===== ai 域：AI 运行时（对话 / 模型清单 / 能力） =====
  {
    code: 'ai:runtime:models',
    domain: 'ai',
    label: '可用 AI 模型列表',
    routePath: '/api/v1/ai/models',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取可用 AI 模型列表',
  },
  {
    code: 'ai:runtime:chat',
    domain: 'ai',
    label: 'AI 对话',
    routePath: '/api/v1/ai/chat/completions',
    httpMethods: ['POST'],
    actions: ['create'],
    description: 'OpenAI 兼容对话接口（SSE 流式）',
  },
  {
    code: 'ai:runtime:capabilities',
    domain: 'ai',
    label: 'AIBase 能力清单',
    routePath: '/api/v1/ai/capabilities',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取 AIBase 能力清单（scopes/skills/tools）',
  },

  // ===== system 域：系统设置 =====
  {
    code: 'system:features:get',
    domain: 'system',
    label: '获取系统功能开关',
    routePath: '/api/v1/system/features',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取系统功能开关',
  },
  {
    code: 'system:features:update',
    domain: 'system',
    label: '更新系统功能开关',
    routePath: '/api/v1/system/features',
    httpMethods: ['PUT'],
    actions: ['update'],
    description: '更新系统功能开关',
  },
  {
    code: 'system:backup:list',
    domain: 'system',
    label: '备份列表',
    routePath: '/api/v1/system/backups',
    httpMethods: ['GET'],
    actions: ['read'],
    description: '获取数据库备份文件列表',
  },
  {
    code: 'system:backup:run',
    domain: 'system',
    label: '执行备份',
    routePath: '/api/v1/system/backups/run',
    httpMethods: ['POST'],
    actions: ['create'],
    description: '立即执行数据库备份',
  },
];

const CATALOG_BY_CODE = BUILTIN_API_CATALOG.reduce((acc, item) => {
  acc[item.code] = item;
  return acc;
}, {});

function getBuiltinApiByCode(code) {
  return CATALOG_BY_CODE[code] || null;
}

function listBuiltinApis() {
  return BUILTIN_API_CATALOG;
}

function existsBuiltinApiCode(code) {
  return Object.prototype.hasOwnProperty.call(CATALOG_BY_CODE, code);
}

module.exports = {
  BUILTIN_API_CATALOG,
  getBuiltinApiByCode,
  listBuiltinApis,
  existsBuiltinApiCode,
};
